const DEVICE_MESSAGE = Symbol.for("DEVICE_MESSAGE");
const DEVICE_COORDINATES = Symbol.for("DEVICE_COORDINATES");
const ONLINE_DEVICES = Symbol.for("ONLINE_DEVICES");

export {
    DEVICE_MESSAGE
    , DEVICE_COORDINATES
    , ONLINE_DEVICES
}