const DB_INSERT_ERROR = Symbol.for("DB_INSERT_ERROR")
const DB_INSERT_SUCCESS = Symbol.for("DB_INSERT_SUCCESS")
const DB_READ_SUCCESS = Symbol.for("DB_READ_SUCCESS")
const DB_READ_ERROR = Symbol.for("DB_READ_ERROR")


export {
    DB_INSERT_ERROR,
    DB_INSERT_SUCCESS,
    DB_READ_SUCCESS,
    DB_READ_ERROR
}