export const objectDetection = (paginationRange=25)=>`objectDetection: objects(
  first: ${paginationRange}
  orderBy:ID_DESC 
    offset: $cursor
    filter:{
      vehicleId:{equalTo:$vehicleId}
      , readingat:{ 
          greaterThanOrEqualTo: $startDateTime
        , lessThanOrEqualTo: $endDateTime
      } 
    }){
    	nodes{
      readingat
      id
      topicId
      topic{
        name
      }
      vehicleId
      message{
        header{
          headerid
          readingat
          seq
          node
        }
        detection{
          header{
            headerid
            readingat
            seq
            node
          }
        	cuboid {
            centroid{
              xM
              yM
              zM
            }
            dimension{
              widthM
              depthM
              heightM
            }
            orientation{
              rollDeg
              pitchDeg
              yawDeg
            }
          }
          roi{
            x
            y
            width
            height
            thetaDeg
          }
          label
          confidence
        }
        centroidRpy{
          rollDeg
          pitchDeg
          yawDeg
        }
        centroidLocation{
          xyzCamera{
            xM
            yM
            zM
          }
          xyzStarfire{
            xM
            yM
            zM
          }
          lla{
            latitudeDeg
            longitudeDeg
            altitudeM
          }
          enu{
            eastM
            northM
            upM
          }
          fieldOrigin{
            latitudeDeg
            longitudeDeg
            altitudeM
          }
          ecef{
            xM
            yM
            zM
          }
        }
        objectMessageVertices{
          nodes{
            xyzCamera{
              xM
              yM
              zM
            }
          }
        }
      }      
    }
  }`